### ISSUE TITLE
Crash when trying to connect to secure network with no password

### ISSUE THREAD

**Issue by zKesten** [ThanosFisherman/WifiUtils#13]
06-19 12:45:02.837 21530-21530/com.roboteam.teamy.usa E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.roboteam.teamy.usa, PID: 21530
    java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.SCAN_RESULTS flg=0x4000010 } in com.thanosfisherman.wifiutils.wifiScan.WifiScanReceiver@c0dcff7
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:876)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5258)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:735)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.thanosfisherman.wifiutils.ConfigSecurities.getWifiConfiguration(ConfigSecurities.java:119)
        at com.thanosfisherman.wifiutils.ConnectorUtils.connectToConfiguredNetwork(ConnectorUtils.java:234)
        at com.thanosfisherman.wifiutils.ConnectorUtils.connectToWifi(ConnectorUtils.java:163)
        at com.thanosfisherman.wifiutils.WifiUtils$2.onScanResultsReady(WifiUtils.java:137)
        at com.thanosfisherman.wifiutils.wifiScan.WifiScanReceiver.onReceive(WifiScanReceiver.java:20)
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:866)
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5258) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:735)

**Comment by gamebrina** [comment]
Same here. Happens when connecting to a known unprotected wifi, but doesn't happen everytime. I think it happens after at least one try. For me it's ConfigSecurities.java:120

Some analysis:
Line com.thanosfisherman.wifiutils.ConfigSecurities.getWifiConfiguration(ConfigSecurities.java:120) looks like 
if (bssid.equals(config.BSSID) || ssid.equals(config.SSID)) {
but bssid is null and bssid is configToFind.BSSID.

config is from ConfigSecurities.getWifiConfiguration where in line 142 all WifiConfigurations are iterated.  Somehow the wifiManager returns a config with BSSID = null, but the ssid matches, so the config is returned and used.


I come up with two solutions, but I don't know if they are good:
A null-check after line 108:
final String bssid = configToFind.BSSID;
if (bssid == null)
  bssid = "any";

or 

A null check in line 120:
if ((bssid != null && bssid.equals(config.BSSID)) || ssid.equals(config.SSID)) {
...

Let me know when I can help!

**Comment by ThanosFisherman** [comment]
Hello guys. A few people told me about this but I can't reproduce it on my device. I think it might be hardware specific issue but I will apply on a defensive fix anyways.

@gamebrina thank you very much for your contribution. I will proceed on a  merge soon.

**Comment by ThanosFisherman** [comment]
I published a new version 1.4.0 that hopefully fixes NPE Crashes.

I'm just gonna leave this issue open for a while in case any related errors come up.

**Comment by fatbads** [comment]
There was an error loading the preference bundle for Wi-Fi: (null) I get this massages when I go in my wifi options and WiFi opinions don't show up can fix it NewTerm-ios10-13  commands
