### ISSUE TITLE
Activity has leaked IntentReceiver

### ISSUE THREAD

**Issue by gabrielmleo** [ThanosFisherman/WifiUtils#7]
Hello man, first of all , congrats for lib, it's very helpful.
I have a problem when perform a search or enable wifi. If I perform these operations a bit faster I catch a leak error, here is the stack trace: 

` Activity com.example.wificonnectionmanager.view.wifilist.WifiListActivity has leaked IntentReceiver com.thanosfisherman.wifiutils.wifiScan.WifiScanReceiver@3d4faf that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                       android.app.IntentReceiverLeaked: Activity com.example.wificonnectionmanager.view.wifilist.WifiListActivity has leaked IntentReceiver com.thanosfisherman.wifiutils.wifiScan.WifiScanReceiver@3d4faf that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                           at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:903)
                                                                                           at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:704)
                                                                                           at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1741)
                                                                                           at android.app.ContextImpl.registerReceiver(ContextImpl.java:1721)
                                                                                           at android.app.ContextImpl.registerReceiver(ContextImpl.java:1715)
                                                                                           at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:496)
                                                                                           at com.thanosfisherman.wifiutils.ConnectorUtils.registerReceiver(ConnectorUtils.java:144)
                                                                                           at com.thanosfisherman.wifiutils.WifiUtils$1.onWifiEnabled(WifiUtils.java:78)
                                                                                           at com.thanosfisherman.wifiutils.wifiState.WifiStateReceiver.onReceive(WifiStateReceiver.java:28)
                                                                                           at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:866)
                                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5259)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)`

These leak error occurs when I perform operations finish activity and than reopen it.
I saw in code that you have unregistered the receivers, so I have no idea what is causing the problem.

**Comment by gabrielmleo** [comment]
I Think I discovered the problem, in Activity when I call one of WifiUtils methods, instead of pass applicationContext I was passing "this" ( activity context instance ), I just change this and leak stopped.

**Comment by ThanosFisherman** [comment]
Hey. Good to know you have worked this around, I'll have a look anyways during the next couple of days in case I missed something but yeah passing `this` instead of `getApplicationContext()` is prone to memory leaks.
