### ISSUE TITLE
transformClassesWithMultidexlistForDebug while compiling

### ISSUE THREAD

**Issue by ArisChoice** [ThanosFisherman/WifiUtils#8]
Error:Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> java.lang.UnsupportedOperationException (no error message)

**Comment by ThanosFisherman** [comment]
I'm not sure how your issue is related to this lib? Please provide some more info. Also make sure your multidex support is configured correctly. (If it's needed at all).

**Comment by ArisChoice** [comment]
**On using:** compile 'com.thanosfisherman.wifiutils:wifiutils:1.3.5'. I am using latest one .
 On compiling my project i  am receiving above error.
----------------------------------
**But on using:**   compile 'com.thanosfisherman.wifiutils:wifiutils:1.3.3'  every thing is ok.
but receiving this error on android version 4.4.2. Is there any solution to fix this plz

 `04-09 12:29:03.298 19789-19789/ E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.SCAN_RESULTS flg=0x8000010 } in com.thanosfisherman.wifiutils.wifiScan.WifiScanReceiver@4178ee18
                                                                                 at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:860)
                                                                                 at android.os.Handler.handleCallback(Handler.java:725)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                 at android.os.Looper.loop(Looper.java:158)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5751)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
                                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                                              Caused by: java.lang.NullPointerException
                                                                                 at com.thanosfisherman.wifiutils.ConfigSecurities.getWifiConfiguration(ConfigSecurities.java:105)
                                                                                 at com.thanosfisherman.wifiutils.ConnectorUtils.connectToConfiguredNetwork(ConnectorUtils.java:268)
                                                                                 at com.thanosfisherman.wifiutils.ConnectorUtils.connectToWifi(ConnectorUtils.java:199)
                                                                                 at com.thanosfisherman.wifiutils.WifiUtils$2.onScanResultsReady(WifiUtils.java:136)
                                                                                 at com.thanosfisherman.wifiutils.wifiScan.WifiScanReceiver.onReceive(WifiScanReceiver.java:20)
                                                                                 at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:845)
                                                                                 at android.os.Handler.handleCallback(Handler.java:725) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                                                 at android.os.Looper.loop(Looper.java:158) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5751) 
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850) 
                                                                                 at dalvik.system.NativeStart.main(Native Method) `
